"""
Django settings for a2 project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# import mongoengine

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@##==#ejzn_a4#2o&o8bwxr(ys2@z0(2_wwu7lw_knahwe=bpi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1','192.168.89.141']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [


    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'dao',
    'corelogic.common',
    'UI.dashboard',
    'nodes',
    'pods',
    'application',
    'corelogic.topology',
    'corelogic.registry',
    'UI.hpa',
    'uat',
    'corelogic.deployment',
    # 'channels',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = [

    'django.contrib.staticfiles.storage.StaticFilesStorage'

]
ROOT_URLCONF = 'a2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'custom_tags': 'application.custom_tags',
            }
        },
    },

]

WSGI_APPLICATION = 'a2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    # 'mongodb': {
    #
    #
    #     'ENGINE': 'django.db.backends.dummy',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'k8s',
        'USER': 'root',
        'PASSWORD': 'allbright',
        # 'HOST': os.environ['PXC_CLUSTER_SERVICE_HOST'],
        'HOST': '192.168.151.44',
        'PORT': '3306',
        # 'OPTIONS': {
        #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        # },

    }

}

# Redis
# REDIS_OPTIONS = {
#     'HOST': '192.168.151.44',
#     'PORT': 6379,
#     'DB': 0
# }
#
# USE_REDIS = True
#
# # Channel settings
# CHANNEL_LAYERS = {
#     "default": {
#         # "BACKEND": "asgiref.inmemory.ChannelLayer",
#         "BACKEND": "asgi_redis.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": ['redis://{}:{}'.format(REDIS_OPTIONS['HOST'],
#                                              REDIS_OPTIONS['PORT'])]
#         },
#         "ROUTING": "a2.routing.channel_routing"
#     }
# }

# SESSION_ENGINE = 'mongoengine.django.sessions'

# AUTHENTICATION_BACKENDS = (
#     'mongoengine.django.auth.MongoEngineBackend',
#
# )

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators


# CACHE_BACKEND = 'db://k8scache?timeout=60'

# CELERY_BROKER_URL = 'redis://192.168.151.15:6379//'
# CELERY_BROKER_URL = 'amqp://admin:admin@192.168.151.15'
# CELERY_RESULT_BACKEND = 'redis://192.168.151.15:6379'
# # CELERY_RESULT_BACKEND = 'amqp://admin:admin@192.168.151.15'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Asia/Hong_Kong'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Logging
LOGGING = {
    'version': 1,
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'formatters': {
        'verbose': {
            'format': '%(asctime)s - %(levelname)s - %(module)s - %(message)s'
        }
    },
    'loggers': {
        'k8s-ui.dashboard': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True
        }
    }
}
