# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdeployoption',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='appimage',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='appname',
            name='all_apptypes',
        ),
        migrations.RemoveField(
            model_name='appname',
            name='app_repository',
        ),
        migrations.RemoveField(
            model_name='apprepository',
            name='app_image',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='group_type',
        ),
        migrations.DeleteModel(
            name='AppDeployOption',
        ),
        migrations.DeleteModel(
            name='AppImage',
        ),
        migrations.DeleteModel(
            name='AppName',
        ),
        migrations.DeleteModel(
            name='AppRepository',
        ),
        migrations.DeleteModel(
            name='AppType',
        ),
        migrations.DeleteModel(
            name='AppVersion',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
    ]
