apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: ca.pem
    server: https://kubernetes.default.svc.cluster.local
users:
- name: kubelet
  user:
    client-certificate: node-registry.pem
    client-key: node-registry-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-cluster.local
current-context: kubelet-cluster.local
