apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: ca.pem
    server: https://192.168.151.40:443
users:
- name: kubelet
  user:
    client-certificate: apiserver.pem
    client-key: apiserver-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-cluster.local
current-context: kubelet-cluster.local
