apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: ca.crt
    server: https://47.52.242.147:8443
users:
- name: kubelet
  user:
    client-certificate: client.crt
    client-key: client.key
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-cluster.local
current-context: kubelet-cluster.local
