apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://k8s-master-elb.allbright.local:443
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/k8s-node-4.pem
    client-key: /etc/kubernetes/ssl/k8s-node-4-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-cluster.local
current-context: kubelet-cluster.local